/*
Navicat PGSQL Data Transfer

Source Server         : roache
Source Server Version : 80309
Source Host           : 192.168.1.114:5432
Source Database       : roacheopen
Source Schema         : public

Target Server Type    : PGSQL
Target Server Version : 80309
File Encoding         : 65001

Date: 2011-03-20 15:24:28
*/


-- ----------------------------
-- Table structure for "public"."golfers"
-- ----------------------------
DROP TABLE "public"."golfers";
CREATE TABLE "public"."golfers" (
"realname" varchar(300) NOT NULL,
"bio" varchar(999),
"currentrank" float8,
"picture" varchar(300),
"scoreaverage" float8,
"status" int2 DEFAULT 2,
"handicap" int2
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of golfers
-- ----------------------------
INSERT INTO "public"."golfers" VALUES (' Billy Bob McWilliams', '<b></b> Even more shocking than having 2 John Joe''s it''s having 2 Billy Bobs. This one has to be the better of the 2 BillyBob''s, and I can''t believe I just wrote that sentence. Has never played a round of golf before but he has been taking a few lessons recently. I will leave him here until I get a scouting report as he is going out for the first time Monday.', '68', '<img src="images/caddyshack1.jpg" alt="Billy Bob McWilliams"   align="left"><BR>', null, '3', null);
INSERT INTO "public"."golfers" VALUES ('Adam Russell', '<b></b> Very Good athlete but he has never played on any golf course other than a miniature one. Very few players can come out thier first time golfing and not be a complete train wreck. Adam could be one of the exceptions but it''s rare. Take him late where there is little risk and hope.', '72', '<img src="images/adamrussell.jpg" alt="Adam Russell"   align="left"><BR>', '150', '1', null);
INSERT INTO "public"."golfers" VALUES ('Another Ioreo', 'waiting on phone call also.', '78', '<img src="images/caddyshack2.jpg" alt="Mark Dlutowski"   align="left"><BR>', null, '2', null);
INSERT INTO "public"."golfers" VALUES ('Big Outside Jim', '<b></b> Will take brake from sitting outside plough to attend tournament. Says he could shot anywhere from a 95 to 125.', '37', '<img src="images/caddyshack4.jpg" alt="Robert from Glam"   align="left"><BR>', '100', '1', null);
INSERT INTO "public"."golfers" VALUES ('Bill Bevin', 'Shoots 95 -98 at byrne.', '29', '<img src="images/caddyshack3.jpg" alt="Ryan'' Friend"   align="left"><BR>', '97.5', '1', null);
INSERT INTO "public"."golfers" VALUES ('Billy Bob from Plough', '<b></b> Once threw up on his own back and won an award for it. Proving that he cannot handle his liquer but is also not afraid to use it. Will be drunk by 3rd hole, watch your back.', '74', '<img src="images/caddyshack1.jpg" alt="Billy Bob from Plough"   align="left"><BR>', '125', '3', null);
INSERT INTO "public"."golfers" VALUES ('Billy Bob''s Dad', 'Good Golfer need an update though.', '54', '	<img src="images/caddyshack10.jpg" alt="Paul Sholette" align="left"><BR>', '85', '3', null);
INSERT INTO "public"."golfers" VALUES ('Blaise Reifer', '<b>Former Winner (2009)</b> Hurt his trigger finger trying to do a drive by so he may be hindered. Good chance he shoots like kevin federline, better chance he comes dressed like him.', '57', '<img src="images/blaisereifer.jpg" alt="Blaise Reifer"   align="left"><BR>', '95', '3', null);
INSERT INTO "public"."golfers" VALUES ('Bob Hopkins', '<b>Former Winner 2008</b> Shot in the 70''s at Juniata.', '5.6', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', null, '3', null);
INSERT INTO "public"."golfers" VALUES ('Bob Knowles', 'Shoots in the low 90''s at good courses. Shot 85 at byrne.', '4', '<img src="images/caddyshack5.jpg" alt="Ron" align="left"><BR>', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Brian Baur', 'Shoots 98-100.', '32', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', '97.5', '2', null);
INSERT INTO "public"."golfers" VALUES ('Brian Breslin', '<b>Former Winner(2000,2001)</b> Recluse, the Bobby Fisher of the Roache Open, Won the first 2 Roache Opens and then disapeared like he was Kaiser Sose.', '53', '<img src="images/caddyshack2.jpg" alt="Brian Breslin"   align="left"><BR>', '115', '3', null);
INSERT INTO "public"."golfers" VALUES ('Brian Fabrizio', 'Need a scouting report.', '14', '<img src="images/caddyshack8.jpg" alt="Ed Tomaselli"   align="left"><BR>', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Brian Fabrizio 1', null, '100', null, null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Brian Fabrizio 2', null, '100', null, null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Brian Fabrizio 3', null, '100', null, null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Brian McCloskey', 'Shoots about a 90 at Five Ponds which is a long course compared to Byrne and a par 71. Probably would shoot mid 80''s at Byrne. I have played on his baseball team and he was our best hitter the year we won the championship. Definite Captain.', '5.9', '<img src="images/caddyshack9.jpg" alt="Ron" align="left"><BR>', '85', '1', '19');
INSERT INTO "public"."golfers" VALUES ('Brian Roache', 'Former Winner (2007) Uncanny ability to hit long puts and chips from fringe with his Giant Gorilla Hands.) Just shot a 96 at Byrnes after not playing for 2 years. ', '45', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi." align="left"><BR>', '105', '3', null);
INSERT INTO "public"."golfers" VALUES ('Chris Barber', 'Has not played in a while says to put him about mid 90''s at Byrne.', '23', '<img src="images/caddyshack7.jpg" alt="Ron" align="left"><BR>', '97.5', '1', null);
INSERT INTO "public"."golfers" VALUES ('Chris Davis(Wink)', '<b>Defending Roach Open Champion. Former Winner(2002,2003,2008)</b> Captained 2003 team to victory at Middletown. Makes Kenny Nolan seem cheerful, can read greens like an idiot savant.Their is no debating Chris Davis''s talent, he has shot in the high seventies, the problem comes from him only playing once a year now with a bad back. Probably would have difficulty scoring by himself but is an extremely valuable best ball player even only playing once a year. Just shot a 107 and then a 92 at Byrne but swung the club well he just kept over or undershooting the green but his balls were right on target. Needs a few rounds to get his feel back and he could drop his score precipitously and be very dangerous, stock going up. Chris has won half of the Roache Opens since 2002.', '19.5', '<img src="images/chrisdavis.jpg" alt="Chris Davis"   align="left"><BR>', '90', '1', '22');
INSERT INTO "public"."golfers" VALUES ('Chris Fahey', 'Shoots between 90-100.', '21.5', '<img src="images/caddyshack3.jpg" alt="Ryan'' Friend"   align="left"><BR', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Chris Staub', 'shoots about an 92 at a par 72.', '12', '<img src="images/caddyshack5.jpg" alt="Ron" align="left"><BR>', '87', '2', '20');
INSERT INTO "public"."golfers" VALUES ('Colleen Breslin', 'Competing in her first Roach Open. Part of a scramble team that shot -4 at John F. Byrne. Student of Dan Hoban and "Sense" Mr. Choi from Juniata Driving Range. Capable of hitting par 3 greens.', '99', '<img src="images/colleenbreslin.JPG" alt="Colleen" align="left"><BR>', '125', '1', null);
INSERT INTO "public"."golfers" VALUES ('Dan Durkin', 'shoots about 85 at byrne', '5.7', '<img src="images/caddyshack3.jpg" alt="Ryan'' Friend"   align="left"><BR', '85', '1', null);
INSERT INTO "public"."golfers" VALUES ('Dan Saunders', 'shoots about an 82 at a par 72.', '1', '<img src="images/caddyshack5.jpg" alt="Ron" align="left"><BR>', '77', '2', '10');
INSERT INTO "public"."golfers" VALUES ('Dave Klatchko', '<b></b> Shoots about a 100 which is probably under a 100 at a place like John F. Byrne.', '61', '<img src="images/caddyshack10.jpg" alt="Dave Klatchko"   align="left"><BR>', null, '2', null);
INSERT INTO "public"."golfers" VALUES ('Dave Upton', 'about 108 at byrne.', '25', null, null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Dave from Plough', '<b></b> Dave''s an Animal. Daves a mess. Shoots about 110.', '47', '<img src="images/caddyshack10.jpg" alt="Dave from Plough"   align="left"><BR>', '110', '1', null);
INSERT INTO "public"."golfers" VALUES ('David Breslin', '<b>Former Winner (2009)</b> Works at best buy if your looking for a HD Plasma he''s your guy, if your looking for help on the golf course look elsewhere. I had his brother John(My Cousin)Breslin on my Team last year and he''s ahhh...how do I say...he''s not good. I am pretty sure David is alot worse.', '69.5', '<img src="images/caddyshack5.jpg" alt="David Breslin"   align="left"><BR>', '125', '1', null);
INSERT INTO "public"."golfers" VALUES ('Dee A.K.A Dees Nutz, A.K.A Dee it Up, A.K.A. Dee Money Shot', '<b></b>  The best Irish Girl in the Tournament, draft accordingly. Said she took some lessons which would be more lessons than any one below her in the rankings. She does not drink so she will be way more sober than anyone below her in the rankings. Way more. Way Way More. Update Dee went to the Range with Rob Pietropaula and he said after some tweeking she was able to hit her 5 iron and driver straight 160. Moving her up.', '70', '<img src="images/caddyshack10.jpg" alt="Dee A.K.A Dees Nutz"   align="left"><BR>', '115', '3', null);
INSERT INTO "public"."golfers" VALUES ('Dennis Nash', '<b>Former Winner(2002)</b> If Kenny doesn''t show up he''s the best Irishman in the Tourny, whatever that means. Shooting around 97 currently at John F. Byrne', '34', '<img src="images/caddyshack9.jpg" alt="Dennis Nash"   align="left"><BR>', '97.5', '1', null);
INSERT INTO "public"."golfers" VALUES ('Dennis Nash Friend', 'Need a scouting report and a name', '100', null, null, '3', null);
INSERT INTO "public"."golfers" VALUES ('Ed Bell', '<b></b> Kim O''Shea says he''s shooting in the 90''s. Can on rare occassion dip into the 80''s.', '15', '<img src="images/caddyshack8.jpg" alt="Michelle"   align="left"><BR>', '92.5', '2', '25');
INSERT INTO "public"."golfers" VALUES ('Ed Bradley', '<b></b> Will intimidate puny opponents with his massive frame. Roache Open does not currently steroid test players so your safe drafting him high. On a course like Byrne Ed could help off the tee if your team is lacking power. Just shot a 111 at John F. Byrne.', '49', '<img src="images/caddyshack11.jpg" alt="Ed Bradley"   align="left"><BR>', '110', '1', null);
INSERT INTO "public"."golfers" VALUES ('Ed McClinick', 'Shoots in high 80''s', '19', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi." align="left"><BR>', '87', '3', '18');
INSERT INTO "public"."golfers" VALUES ('Ed Tomaselli', '<b>Former Winner (2009)</b> Last time out shot a 96 at Byrne. I Talked to him he normally shoots in the low 90''s. Shot in the 80''s out with mike this year at Byrne. Also shot a 78 at Byrne this year.', '5', '<img src="images/caddyshack8.jpg" alt="Ed Tomaselli"   align="left"><BR>', '92.5', '1', '22');
INSERT INTO "public"."golfers" VALUES ('Ed tommaselli frien', 'shoots in the 90''s', '30', null, null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Edward O''Brien(Pony)', '<b>Former Winner (2003,2005)</b> Lefthanded, looks like ralph macchio, has a similiar golf game. You could make an argument to rank him higher and he still might be if he gets out at all this year. Just shot a 90 something at cobb which would put him atleast low 90''s at Byrne.', '13', '<img src="images/edobrien.jpg" alt="Edward O''Brien(Pony)"   align="left"><BR>', '90', '1', '25');
INSERT INTO "public"."golfers" VALUES ('Erin''s Dad', 'Erin''s (One of our 2 Beer Girls) Dad shoots about an 85 on par 70-72''s. This would put him at the Top of the Draft', '2', '<img src="images/caddyshack9.jpg" alt="Ron" align="left"><BR>', '85', '3', '13');
INSERT INTO "public"."golfers" VALUES ('Erin''s Dad''s Friend', 'Need a scouting report from Erin or her Dad. Going to rank him in the middle in the mean time.', '3', '<img src="images/caddyshack1.jpg" alt="Ron" align="left"><BR>', '90', '3', null);
INSERT INTO "public"."golfers" VALUES ('George Kamerly', 'shoots a 94. Don''t know what course.', '28', '<img src="images/johnglam.jpg" alt="Bob."   align="left"><BR>', '52.2', '1', null);
INSERT INTO "public"."golfers" VALUES ('George Riley', '115.', '66', '<img src="images/caddyshack10.jpg" alt="Paul Sholette"   align="left"><BR>', '115', '2', null);
INSERT INTO "public"."golfers" VALUES ('Greg O''Connor', '<b></b> Big hitter the lama, Long, once broke his 5 Iron on a sprinkler head and was unfazed,may provide comic relief but not relief from hazards. Once drove his whole car into a pond, won''t think twice about driving his ball into one.', '52', '<img src="images/gregoconnor.jpg" alt="Greg O''Connor"   align="left"><BR>', '115', '1', null);
INSERT INTO "public"."golfers" VALUES ('Jamie Magee', '<b></b> Out: No not out of the closest as most whould have geussed. NO he''s Going Back to Maryland to be with his wife and kids. Plays alot of Tiger Woods Golf, only problem is he''ll have to use a club instead of a joystick. Has been playing just good enough to put him ahead of atleast 3 players right now.', '73', '<img src="images/jamiemagee.jpg" alt="Jamie Magee"   align="left"><BR>', '125', '1', null);
INSERT INTO "public"."golfers" VALUES ('Jason Kemner', '<b></b> Returning to his 2nd Roache Open appearence. Jason says he''s been shooting around 100.', '36', '<img src="images/caddyshack8.jpg" alt="Jason Kemner"   align="left"><BR>', '97.5', '2', null);
INSERT INTO "public"."golfers" VALUES ('Jim Breslin', '<b>Former Winner(2007)</b> Strategy for tournament revolves completely around avoiding picking Jim Roache at all costs. Training like I was Rocky before he fought Drago, running up hills with 3 golf bags strapped to my back with a five iron clenched in my teeth and chasing chickens around the putting green. Plan on studying film by watching Caddyshack. last rounds byrne(83,85,85,89) FDR(97)', '5.8', '<img src="images/greenman.jpg" alt="Jim Breslin."   align="left"><BR>', '85', '1', '18');
INSERT INTO "public"."golfers" VALUES ('Jim Campbell', '<b>Former Winner (2001)</b> If this was a golf cart race he would be ranked 1st overall. This is not a golf cart race.', '51', '<img src="images/caddyshack4.jpg" alt="Jim Campbell"   align="left"><BR>', '115', '1', null);
INSERT INTO "public"."golfers" VALUES ('Jim Goring', 'If you draft Jim your wildest dreams will come true.', '100', '<img src="images/johnglam.jpg" alt="Bob."   align="left"><BR>', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Jim Riley', '115.', '64', '<img src="images/caddyshack10.jpg" alt="Paul Sholette"   align="left"><BR>', '115', '1', null);
INSERT INTO "public"."golfers" VALUES ('Jim Roache', '<b>Former Winner (2000,2001,2004)</b>Venerable founder of the Roache Open Tournament.Plays small ball, ironically also has very small balls. Stock is dropping faster than one of his duffed tee shots. With all due respect to mentally challenged primates everywhere, his swing looks like a retarded, drunk monkey trying to whack his own tail with a seven iron. At this stage of his long career he is nothing more than a specialty player. Has no long game to speak of but has a good short game around the green and in the bedroom. In some states swinging a club like he does with people around is considered attempted assault. Update: Roache is now under the tuteledge of Mr. Kim From Juniata. Though in typical Jim Roache Fashion he is still using a gimmick "Moe Norman" Drive. He has shot several rounds under 90 at Byrne. His drives are short, about 190-200. Has petitioned rules committee for eligibility to tee off from Ladies Tees,which is currently under review.last rounds byrne(89,88,95)', '20.5', '<img src="images/jimroache.jpg" alt="Jim Roache"   align="left"><BR>', '100', '1', null);
INSERT INTO "public"."golfers" VALUES ('Joe Chic', '<b></b> Need a scouting report from Joe Chic. Got one, Joe shoots in the 90''s usually at bensalem. Says he is about bogey golf, but is not really sure as he doesn''t keep score like Ty Webb, so I am ranking him here as a precautinary measure.', '26.7', '<img src="images/caddyshack5.jpg" alt="Ron" align="left"><BR>', '90', '1', null);
INSERT INTO "public"."golfers" VALUES ('Joe Keene', 'Vulnerable to chops to the neck. Shoots about a 105.', '39', '<img src="images/caddyshack11.jpg" alt="Tim Roache."   align="left"><BR>', null, '3', null);
INSERT INTO "public"."golfers" VALUES ('Joe Keene''s Friend', 'Shoots about a 110.', '56', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', null, '2', null);
INSERT INTO "public"."golfers" VALUES ('Joe Riley', '115.', '63', '<img src="images/caddyshack10.jpg" alt="Paul Sholette"   align="left"><BR>', '115', '1', null);
INSERT INTO "public"."golfers" VALUES ('Joe Wicker', '<b></b> Uses his freakishly large but talented nose like a plumb line to check for breaks in green. Just shot a 117 at John F. Byrne. Chance he helps your team or remains fully clothed are both 10%.', '63.5', '<img src="images/caddyshack5.jpg" alt="Joe Wicker"   align="left"><BR>', '115', '1', null);
INSERT INTO "public"."golfers" VALUES ('John Austin', '<b></b> Wiley golf veteran. Moving him back based on other players getting better and that he will probably try to draft his nephews Stepen Pietropala and Jamie Magee(see below). Just shot a 98 at Island Green which is a tough course, that score translates to atleast low 90''s at Byrne. John says this is about typical of what he shoots.', '31', '<img src="images/caddyshack3.jpg" alt="Uncle John."   align="left"><BR>', null, '2', null);
INSERT INTO "public"."golfers" VALUES ('John Bauer(Cups)', '<b>Former Winner (2005,2009)</b> Will put the ball in the ''Cup'' for you. Need to know how he is shooting or if he is so I can move him up,down. Just shot a 90 at course that translates to mid 80''s at Byrne.', '6', '<img src="images/johnbauer.jpg" alt="John Bauer(Cups)"   align="left"><BR>', '87.5', '3', '18');
INSERT INTO "public"."golfers" VALUES ('John Breslin', '<b></b> Looks more like Jim Breslin plays more like Brian Breslin, this is not a good combination.', '76', '<img src="images/caddyshack4.jpg" alt="John Breslin"   align="left"><BR>', '150', '1', null);
INSERT INTO "public"."golfers" VALUES ('John Demasi', 'Shoots about a 110 at John F. Byrne', '48', '<img src="images/caddyshack1.jpg" alt="John" align="left"><BR>', '105', '1', null);
INSERT INTO "public"."golfers" VALUES ('John Joe Devlin', '<b></b>  Even if he is a good golfer it won''t matter because he will be so hammered  by the 5th hole that you''ll wish you drafted a bag of tees instead. He says  he won''t be drinking on the course if so this is a good spot he shoots about  110. Which at Byrne would translate to 106-108. He''s Scottish and remember the  Scots invented Golf. Putts like a #1.', '37.8', '<img src="images/caddyshack2.jpg" alt="John Joe Devlin"   align="left"><BR>', '105', '1', null);
INSERT INTO "public"."golfers" VALUES ('John Joe Mcsorley', '<b></b> Mike Murrin''s cousin, not as good of a golfer as mike, but much less annoying. Would possibly be in the Top Flight but we in the Top Flight have a don''t ask don''t tell policy. Shockingly not the only player named John Joe in the Tournament.', '50', '<img src="images/johnjoemcsorley.jpg" alt="John Joe Mcsorley"   align="left"><BR>', '97.5', '1', null);
INSERT INTO "public"."golfers" VALUES ('John Mclain', '<b></b> Drive Hard IV The Homey Slice. Has shot in the 90''s before in his best rounds, but now is a 100-110 player.', '42', '<img src="images/caddyshack5.jpg" alt="John Mclain"   align="left"><BR>', '105', '1', null);
INSERT INTO "public"."golfers" VALUES ('John from Glam', '<b></b> Moving Big John up 15 slots based on his round of 84 and an Eagle at John F. Byrne. Former 90''s shooter has found his stroke and is on a hot streak. Don''t want to move him too high too quick but this spot seems about right. last rounds Byrne(94)', '13.5', '<img src="images/johnglam.jpg" alt="Bob."   align="left"><BR>', '92.5', '1', '23');
INSERT INTO "public"."golfers" VALUES ('Kenny Nolan', '<b>Former Winner (2002)</b> He''s like a Pint of Guiness, Irish and bitter but very good. Hasn''t golfed or hit the range. Stock going down but not too far.', '20', '<img src="images/caddyshack4.jpg" alt="Kenny Nolan"   align="left"><BR>', '92.5', '3', '19');
INSERT INTO "public"."golfers" VALUES ('Kenny Nolan''s Brother', null, '40.44', '<img src="images/caddyshack4.jpg" alt="Kenny Nolan"   align="left"><BR>', null, '3', null);
INSERT INTO "public"."golfers" VALUES ('Kevin Kelly', 'Shoots about a 105 at byrne. kenny G not touring philly this summer so he will be at tournament.', '38.1', null, '105', '1', null);
INSERT INTO "public"."golfers" VALUES ('Kim O''Shea', '<b></b> I''ve gotten an update from Kim and she is now shooting in the 90''s.', '67', '<img src="images/caddyshack6.jpg" alt="Kim O''Shea"   align="left"><BR>', '95', '2', null);
INSERT INTO "public"."golfers" VALUES ('Larry Rider', '<b></b> He''s Irish, Padraig Harrington''s Irish, This is where the comparison ends.', '77', '<img src="images/larryryder.jpg" alt="Larry Rider"   align="left"><BR>', '150', '3', null);
INSERT INTO "public"."golfers" VALUES ('Len Ross', 'About a 105 at Byrne.', '40', null, '105', '2', null);
INSERT INTO "public"."golfers" VALUES ('Louie', 'Short and Fast also makes the best coffee and sandwiches in olde city. This may come in more handy than his golf game.', '80', '<img src="images/caddyshack3.jpg" alt="Uncle John."   align="left"><BR>', '150', '2', null);
INSERT INTO "public"."golfers" VALUES ('Marcello Rodriguez', '<b>Former Winner(2004)</b> Lefthanded, very defensive oriented, though i don''t know how that will help you in golf.', '58', '<img src="images/caddyshack2.jpg" alt="Marcello Rodriguez"   align="left"><BR>', '110', '3', null);
INSERT INTO "public"."golfers" VALUES ('Marcus Ryker', 'Shoots in the low to mid 90''s at Byrne.', '22', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', '92.5', '2', null);
INSERT INTO "public"."golfers" VALUES ('Mark Dlutowski(Marky D)', '<b></b> Eccentric player uses clubs from 1906, if mark has gotten out this year we will move him up. waiting on report from Mark. We always rank Mark very high based on his golfing performances of 20 years ago which was probably unfair. We are taking some of the pressure off him this year. Got an update from Mark he says put him down for low to mid 90''s. Mark used to live right down the street from Byrne so I sure he already Byrnes adusted his scores.', '17', '<img src="images/caddyshack2.jpg" alt="Mark Dlutowski"   align="left"><BR>', '92.5', '1', '22');
INSERT INTO "public"."golfers" VALUES ('Mark Stalarski', 'Waiting on a scouting report, expecting it to be bad.', '49', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Michelle Forrest', '<b></b> Starting playing last year but is pretty good. Scouting report from her friend Kim is that she is shooting in the 90''s.', '37.8', '<img src="images/caddyshack7.jpg" alt="Michelle"   align="left"><BR>', '95', '1', null);
INSERT INTO "public"."golfers" VALUES ('Mike Breslin', 'Another horrible Breslin Golfer. Makes Dave Breslin look like Ben Hogan.', '76.4', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Mike Campalone', 'Shoots 95-98 at byrne.', '28', '<img src="images/caddyshack3.jpg" alt="Ryan'' Friend"   align="left"><BR>', '97.5', '2', null);
INSERT INTO "public"."golfers" VALUES ('Mike Eckmyer', '<b></b> Him and Madonna both go by one name and have similiar golf games.', '60', '<img src="images/caddyshack3.jpg" alt="Mike Eckmyer"   align="left"><BR>', '110', '1', null);
INSERT INTO "public"."golfers" VALUES ('Mike Eroh', '<b></b>  Shoots high 90''s at Byrne, high 100''s every where else.', '36', '<img src="images/caddyshack3.jpg" alt="Mike Eckmyer"   align="left"><BR>', '108', '1', null);
INSERT INTO "public"."golfers" VALUES ('Mike Ioreo', 'waiting on phone call.', '79', '<img src="images/caddyshack2.jpg" alt="Mark Dlutowski"   align="left"><BR>', null, '2', null);
INSERT INTO "public"."golfers" VALUES ('Mike Kobilnyk', 'shoots a 95 don''t know what courses. if it''s a good one he could shoot low 90''s at byrne if not below.', '21.5', '<img src="images/caddyshack3.jpg" alt="Ryan'' Friend"   align="left"><BR', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Mike Murrin', '<b></b> Just as annoying as he is good, and he is very annoying, which means he is very good. If he is on you could easily ride him to a championship. Just shot an 89 and 85 at Byrne but is easily capable of low 80''s or high 70''s. He is still on Double Secret Probation from a violation in 2002. He still remains ranked high as a re-instatement penalty. Mike also has a restraining order against him. He is not allowed within 10ft of a scoring pencil. If you get drafted by Mike my advice to you is to start drinking heavily. Update on mike is he just shot a 79 at byrne with what only could be described as a WW1 Bandage wrapped aournd his head. If your any of the nationalitys we fought in WW1 I would watch my back around Mike.', '7', '<img src="images/mikemurrin.jpg" alt="Mike Murrin."   align="left"><BR>', '85', '1', '18');
INSERT INTO "public"."golfers" VALUES ('Nick Prosperi', '<b>Former Winner(2001,2005)</b> Always drafts first and still led 2 teams to titles, 2001,2005,consistent,solid, waiting for scouting report from nick so i can adjust. According to Tim Roache Nick is a notch above himself.', '3.8', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', '82.5', '1', '15');
INSERT INTO "public"."golfers" VALUES ('Nick Taweel AKA (Nick the Real Deal Taweel)', '<b></b>  A rarity, a doctor who hasn''t played golf in over 2 years and with good reason.', '62', '<img src="images/caddyshack2.jpg" alt="Marcello Rodriguez"   align="left"><BR>', '105', '1', null);
INSERT INTO "public"."golfers" VALUES ('Ollie', 'Shoots about a 97 at Byrne.', '35', '<img src="images/caddyshack1.jpg" alt="Ollie" align="left"><BR>', '97.5', '2', null);
INSERT INTO "public"."golfers" VALUES ('Paul Sholette', '<b></b> Could help extra by using his engineering skills to calculate distance using the sun,flag,ball and Pythagorean Theorem. Putting paul as a drafter so he can draft Dave Klatchko his friend. Before anyone complains this is a disadvantage to Paul and his team as Paul would normally be ranked around 19th or 20th.', '33', '<img src="images/caddyshack10.jpg" alt="Paul Sholette"   align="left"><BR>', '100', '3', null);
INSERT INTO "public"."golfers" VALUES ('Rich Scully', 'Shoots about a 100.', '37.5', '<img src="images/caddyshack4.jpg" alt="Kenny Nolan"   align="left"><BR>', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Rob Pietropaula AKA (The Crime Dog) AKA (Super Rob) AKA (The Robber Baron)', '<b>Former Winner (2003, 2008)</b>Shown on left without cape wearing the Roache Open Trophy. Rob is a disciple of the Yoda like Mr. Kim from Fisher''s Glen Driving Range in Juniata, the entrance of which conspicuously looks like the Bat Cave entrance... Chased and caught a purse snatcher from 2nd and Chestnut to Broad and Diamond using a waitress, busboy, Cab Driver, Septa Worker, GPS and singleness of purpose. Tenacious or Over Zealous, you decide. Ability to Stop Trains and Crime. If you draft Rob all your belongings will be safe. A chance he may be called away on mission and take off in cart down Frankford Avenue armed with a 4-iron in lance position. Draft accordingly. last rounds(Byrne 96)', '21', '<img src="images/robpietropaula.jpg" alt="Rob Pietropaula."   align="left"><BR>', '95', '1', '25');
INSERT INTO "public"."golfers" VALUES ('Robert Miller', '<b></b>  His brother is a pro Golfer. This gives him just enough pedigree to move him up from last year. Ability to hit close to pin from 50 yards and in with nice wedge shot. Capable of shooting in the low 90''s.', '24', '<img src="images/robertmiller.jpg" alt="Robert Miller"   align="left"><BR>', '95', '3', null);
INSERT INTO "public"."golfers" VALUES ('Ron Schultz', '<b></b>Returning for his 2nd straight Roache Open. Shoots about a 90.', '14', '<img src="images/caddyshack1.jpg" alt="Ron" align="left"><BR>', '87.5', '2', '20');
INSERT INTO "public"."golfers" VALUES ('Russ Posey', 'In high school he hit Jim Breslin in the face and stole Rob Pietropaula''s girlfriend. Now who could blame him for hitting Jim Breslin in the face(who among you hasn''t wanted to do that), but stealing Rob''s girlfriend is just disturbing cause I have seen the girls Rob dated in high school. His self described anaylisis of his game is "I would describe my game as mostly cloudy with a chance of greatness I will mostly shoot in the 90''s".', '27', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', '95', '1', null);
INSERT INTO "public"."golfers" VALUES ('Russian Steve', '<b></b> Fast, with a plus arm, good looking in shape and speaks Russian. None of these things will help you on a golf course.', '46', '<img src="images/caddyshack6.jpg" alt="Russian Steve"   align="left"><BR>', '110', '1', null);
INSERT INTO "public"."golfers" VALUES ('Ryan Prosperi', '<b></b> Tim Roache''s nephew, apparently Tim has been golfing with him so it shouldn''t be hard to get a scouting report as soon as Tim comes back from vacation. Got a scouting report shoots about a 105 at John F. Byrne', '48', '<img src="images/caddyshack5.jpg" alt="John Joe Mcsorley"   align="left"><BR>', '105', '2', null);
INSERT INTO "public"."golfers" VALUES ('Ryan Prosperi''s Friend', '<b></b> Waiting on scouting report. Got a scouting report from Tim Roache, shoots about a 105 at John F. Byrne', '50', '<img src="images/caddyshack3.jpg" alt="Ryan'' Friend"   align="left"><BR>', '105', '2', null);
INSERT INTO "public"."golfers" VALUES ('Stephen Pietropaula', '<b></b> May hurt you with random loud outburts at his own players. Left Handed. Volatile. Didn''t know where to put him, he is a prodigy of sorts, capable of hitting great shots but also capable of looking like one of worst players out there around the green. Sleeper. Expected due date of child is August 2nd so he might not be available.', '68', '<img src="images/caddyshack7.jpg" alt="Steven Pietropaula"   align="left"><BR>', '110', '1', null);
INSERT INTO "public"."golfers" VALUES ('Steve Maiale', '<b>Former Winner(2000)</b>Steve Maiale is a Golf Goon. Distracting opponents with random outburts of shouting. This may be the only way he can help you, sort of like a 4th line checker.', '70.5', '<img src="images/caddyshack11.jpg" alt="Tim Roache."   align="left"><BR>', null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Steve O''Connell', 'Shoots about an 85.', '3.5', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi."   align="left"><BR>', '85', '1', '18');
INSERT INTO "public"."golfers" VALUES ('Steve O''Conoll''s friend', 'shoots about 105', '38', null, null, '1', null);
INSERT INTO "public"."golfers" VALUES ('Steve Santone', 'Shoots 105-110.', '41', '<img src="images/caddyshack1.jpg" alt="Ron" align="left"><BR>', '105', '2', null);
INSERT INTO "public"."golfers" VALUES ('Ted Malampy', 'Hasn''t played in a while, probably about high 90''s to 100, with occasional long drives you can use. Has a range finder for distances and isn''t afraid to use it. Even though he hasn''t played in a while i guarantee he finds a way to help the team', '25', '<img src="images/caddyshack3.jpg" alt="Nick Prosperi." align="left"><BR>', '97.5', '2', null);
INSERT INTO "public"."golfers" VALUES ('Tim Roache', '<b>Former Winner(2000,2004)</b> Captained 2 teams to titles,2000,2004, waiting for his scouting report on how he''s shooting and will adjust accordingly by a few spots. Recently shot an 84 at John F. Byrne(par 67) and and a 90 at a par 70. Just won longest Drive at Beefseekers tournament.', '5.71', '<img src="images/caddyshack11.jpg" alt="Tim Roache."   align="left"><BR>', '85', '1', '19');
INSERT INTO "public"."golfers" VALUES ('Warren', 'I talked to Warren he hasn''t played golf since 2004, and at the time was probably about a 100+ shooter.', '65', '	<img src="images/caddyshack10.jpg" alt="Paul Sholette" align="left"><BR>', '115', '2', null);

-- ----------------------------
-- Alter Sequences Owned By 
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table "public"."golfers"
-- ----------------------------
ALTER TABLE "public"."golfers" ADD PRIMARY KEY ("realname");
